---
all:
    hosts:
        #192.168.56.4:
        192.168.1.54:
            wireguard_address: 10.9.0.1/32
            wireguard_allowed_ips: "10.9.0.1/32, 192.168.2.0/24"
            wireguard_endpoint: vpn.brunoy-osteopathe.fr
