---
all:
    hosts:
        192.168.1.17:
            wireguard_address: 10.9.0.1/32
            wireguard_allowed_ips: "10.9.0.2/32"
            wireguard_endpoint: 192.168.1.17
            ansible_ssh_private_key_file: .../MedShakeEHR-Ansible/.vagrant/machines/medshakeehr/virtualbox/private_key
            ansible_ssh_user: vagrant
            ansible_ssh_port: 22
        
        192.168.1.18:
            wireguard_address: 10.9.0.1/32
            wireguard_allowed_ips: "10.9.0.1/32"
            wireguard_endpoint: 192.168.1.17
            ansible_ssh_private_key_file: .../MedShakeEHR-Ansible/.vagrant/machines/client/virtualbox/private_key
            ansible_ssh_user: vagrant
            ansible_ssh_port: 22

