---
all:
    hosts:
        192.168.1.17:
            wireguard_address: 10.9.0.1/32
            wireguard_endpoint: 192.168.1.17
        
        192.168.1.18:
            wireguard_address: 10.9.0.1/32
            wireguard_endpoint: ""

