---
- name: Installation medshakehr
  hosts: 192.168.1.17
  become: true
  become_user: root
  vars_files:
    - vars/main.yml

  roles:
    - { role: devsec.hardening.os_hardening, tags: ['OS-sec', 'security', 'base'] }
    - { role: devsec.hardening.ssh_hardening, tags: ['SSH-sec', 'security', 'base'] }
    - { role: geerlingguy.firewall, tags: ['Firewall', 'security', 'base'] }
    - { role: jnv.unattended-upgrades, tags: ['AutoUpgrades', 'security', 'base'] }
    - { role: geerlingguy.mysql, tags: ['MariaDB', 'base', 'minimal'] }
    - { role: devsec.hardening.mysql_hardening, tags: ['MariaDB-sec', 'security', 'base'] }
    - { role: geerlingguy.php, tags: ['PHP', 'base', 'minimal'] }
    - { role: MedShakeEHR, tags: ['MedShakeEHR', 'base', 'minimal'] }
    - { role: geerlingguy.apache, tags: ['Apache', 'base', 'minimal'] }
    - { role: Apache-sec, tags: ['Apache', 'security', 'base'] }

- name: Installation vpn client
  hosts: all
  become: true
  become_user: root
  vars_files:
    - vars/main.yml

  roles:
    - { role: githubixx.ansible_role_wireguard, tags: ['VPN', 'security', 'VPN']}

...
