---
- name: Installation medshakehr
  hosts: medshakeehr
  become: true
  pre_tasks:
    - name: Update package cache
      apt:
        update_cache: true
  roles:
    - role: marsante.medshakeehr
      tags:
        - MedShakeEHR
        - minimal

- name: Installation vpn client
  hosts: all
  become: true
  roles:
    - role: githubixx.ansible_role_wireguard
      tags:
        - VPN
        - security
