---
- name: Installation medshakehr
  hosts: medshakeehr
  become: true
  pre_tasks:
    - name: Update package cache
      apt:
        update_cache: true
  roles:
    - role: marsante.medshakeehr
      tags:
        - MedShakeEHR
        - minimal
    - role: devsec.hardening.mysql_hardening
      tags:
        - MariaDB-sec
        - security
    - role: devsec.hardening.os_hardening
      tags:
        - OS-sec
        - security
    - role: devsec.hardening.ssh_hardening
      tags:
        - SSH-sec
        - security
    - role: geerlingguy.firewall
      tags:
        - Firewall
        - security
    - role: hifis.unattended_upgrades
      tags:
        - AutoUpgrades
        - security

# - name: Installation vpn client
#   hosts: all
#   become: true
#   roles:
#     - role: githubixx.ansible_role_wireguard
#       tags:
#         - VPN
#         - security