---
- name: Installation medshakehr
  hosts: medshakeehr
  become: true

  roles:

    - { role: medshakeehr, tags: ['MedShakeEHR', 'base', 'minimal'] }
    - { role: devsec.hardening.mysql_hardening, tags: ['MariaDB-sec', 'security', 'base'] }
    - { role: geerlingguy.apache, tags: ['Apache', 'base', 'minimal'] }
    - { role: apache_hardening, tags: ['Apache', 'security', 'base'] }
    - { role: devsec.hardening.os_hardening, tags: ['OS-sec', 'security', 'base'] }
    - { role: devsec.hardening.ssh_hardening, tags: ['SSH-sec', 'security', 'base'] }
    - { role: geerlingguy.firewall, tags: ['Firewall', 'security', 'base'] }
    - { role: jnv.unattended-upgrades, tags: ['AutoUpgrades', 'security', 'base'] }

- name: Installation vpn client
  hosts: all
  become: true

  roles:
    - { role: githubixx.ansible_role_wireguard, tags: ['VPN', 'security']}
...
