---
roles: 
  - name: geerlingguy.firewall
  - name: jnv.unattended-upgrades
  - name: geerlingguy.apache
  - name: geerlingguy.php
  - name: geerlingguy.mysql
    src: git+https://github.com/geerlingguy/ansible-role-mysql.git

collections:
  - name: devsec.hardening


