---
roles: 
  - name: geerlingguy.firewall
  - name: jnv.unattended-upgrades
  - name: geerlingguy.apache
  - name: geerlingguy.php
  - name: githubixx.ansible_role_wireguard
  - name: geerlingguy.mysql

collections:
  - name: devsec.hardening


