---
roles: 
  - name: marsante.ansible_role_medshakeehr
  - name: geerlingguy.firewall
  - name: hifis.unattended_upgrades
  - name: githubixx.ansible_role_wireguard
  
collections:
  - name: devsec.hardening


