---
galaxy_info:
    author: "Michaël Val"
    description: 'This Ansible role install the latest version of MedShakeEHR'
    license: GPL-3.0-only
    min_ansible_version: '2.9'
    platforms:
    - name: Debian
      versions:
        - stretch
        - buster
dependencies: []