---
timezone: "Europe/Paris"
msehr_package: ['composer','curl','ghostscript','git','grub','imagemagick','ntp','pdftk','python-pip','wget']
msehrPath: "/home/ehr"
countryName: FR
localityName: Paris
organizationName: Dr Strange
emailAdress: email@domain.tld
orthancUser: user
orthancPswd: orthancPswd